;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Abilities.Skill.ShottBullet",NewTagName="Abilities.Skill.ShootBullet")
+GameplayTagList=(Tag="Abilities.Reactions.Spooked",DevComment="")
+GameplayTagList=(Tag="Abilities.Skill.LaserBeam",DevComment="")
+GameplayTagList=(Tag="Abilities.Skill.ShootBullet",DevComment="")
+GameplayTagList=(Tag="Damage.Conditions.Immune",DevComment="")
+GameplayTagList=(Tag="Data.Default.Damage",DevComment="")
+GameplayTagList=(Tag="DOT.Poison.Cooldown",DevComment="")
+GameplayTagList=(Tag="DOT.Poison.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Death",DevComment="")
+GameplayTagList=(Tag="Faction.Enemy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DamageNumber",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Tower.MachineGunFire",DevComment="")
+GameplayTagList=(Tag="State.Death.End",DevComment="")
+GameplayTagList=(Tag="State.Death.Start",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="SetByCaller base damage")
+GameplayTagList=(Tag="Damage.Kinetic",DevComment="")
+GameplayTagList=(Tag="Damage.Explosive",DevComment="")
+GameplayTagList=(Tag="Damage.Energy",DevComment="")
+GameplayTagList=(Tag="Damage.Pure",DevComment="")
+GameplayTagList=(Tag="Armor.Light",DevComment="")
+GameplayTagList=(Tag="Armor.Medium",DevComment="")
+GameplayTagList=(Tag="Armor.Heavy",DevComment="")
+GameplayTagList=(Tag="Armor.Building",DevComment="")
